services:
  - type: web
    name: saini-txt-direct
    plan: free
    env: docker
    dockerfilePath: Dockerfile
    repo: https://github.com/nikhilsainiop/Saini-txt-direct
    branch: main
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: OWNER
        sync: false
      - key: CREDIT
        sync: false
      - key: CLASSPLUS_EMAIL
        value: saun789.9@gmail.com
      - key: CLASSPLUS_PASSWORD
        sync: false
      - key: CLASSPLUS_LOGIN_URL
        value: https://web.classplusapp.com/api/login
      #- key: WEBHOOK
        #sync: false
      - key: PORT
        value: 8000  # Default port value, update if needed
